name: Puppet Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PDK
        run: |
          wget -q https://apt.puppet.com/puppet-tools-release-jammy.deb
          sudo dpkg -i puppet-tools-release-jammy.deb
          sudo apt-get update -qq
          sudo apt-get install -y pdk
      - name: PDK Validate
        run: pdk validate --parallel

  unit-test:
    name: Unit Tests (Puppet ${{ matrix.puppet }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        puppet: ['8']
    steps:
      - uses: actions/checkout@v4
      - name: Install PDK
        run: |
          wget -q https://apt.puppet.com/puppet-tools-release-jammy.deb
          sudo dpkg -i puppet-tools-release-jammy.deb
          sudo apt-get update -qq
          sudo apt-get install -y pdk
      - name: Run Unit Tests
        run: pdk test unit --puppet-version=${{ matrix.puppet }}
